In [ ]:
import pandas as pd

sca_path = pd.read_csv('raw_data/UIB_SCA_Daily_25Year_with500mscale.csv')
sca_path.head()

In [ ]:
sca_path["sca_km2"].plot()

In [ ]:
import numpy as np
sca_path['sca_km2']= sca['sca_km2'].replace(-9999, np.NAN)
sca['sca_km2']= sca['sca_km2'].interpolate(method= 'linear')

In [ ]:
sca_path['sca_km2'].plot()

In [ ]:
sca_path.describe()

In [ ]:
import matplotlib.pyplot as plt
sca_path.hist(bins=50, figsize=(8,5))
plt.show()

tail heavy data

In [ ]:
sca_path['date']=pd.to_datetime(sca_path['date'])

sca_monthly= sca_path.set_index('date').resample('ME').mean()

In [ ]:
sca_monthly['sca_km2'].plot()

In [ ]:
sca_monthly.head(20)

In [ ]:
sca_monthly.to_csv('sca_monthly_final.csv', index=True)

precipitation

In [ ]:
precip= pd.read_csv('raw_data/precipitation_daily_till2025.csv')
precip.head()

In [ ]:
precip['precip_mm_hr'].plot()

In [ ]:
precip.describe()

In [ ]:
import datetime


precip['date']= pd.to_datetime(precip['date'])
precip_monthly= precip.set_index('date').resample('ME').sum()

In [ ]:
precip_monthly.head()

In [ ]:
precip_monthly.to_csv('precip_monthly_final.csv')

radiation

In [ ]:
radiation=pd.read_csv('raw_data/radiation.csv')
radiation.head()

In [ ]:
radiation.plot()

In [ ]:
radiation['MJ/m2']=radiation['surface_net_solar_radiation_J/m²']/1e6

In [ ]:
radiation.head()

In [ ]:
radiation['date']= pd.to_datetime(radiation['date'])
radiation_monthly= radiation.set_index('date').resample('ME').sum()

In [ ]:
radiation_monthly.head()

In [ ]:
radiation_monthlymj=radiation_monthly.drop('surface_net_solar_radiation_J/m²',axis=1)

In [ ]:
radiation_monthlymj.to_csv('radiation_final.csv')

dewpoint_temp

In [ ]:
dew=pd.read_csv('raw_data/dewpoint_temp.csv')
dew.head()

In [ ]:
dew['mean_dew'].plot()

In [ ]:
dew['date']=pd.to_datetime(dew['date'])
dew_monthly=dew.set_index('date').resample('ME').mean()

In [ ]:
dew_monthly.head()

In [ ]:
dew_monthly.to_csv('dewpoint_temp_final.csv')

NDVI

In [ ]:
ndvi= pd.read_csv('raw_data/NDVI_16day_combined.csv')
ndvi.head()

In [ ]:
ndvi['date']= pd.to_datetime(ndvi['date'])
ndvi_monthly= ndvi.set_index('date').resample('ME').mean()

In [ ]:
ndvi_monthly.head()

In [ ]:
ndvi_monthly.to_csv('ndvi_final.csv')

temp

In [ ]:
import pandas as pd

temp= pd.read_csv('raw_data/temperature2000_2025.csv')
temp['date']= pd.to_datetime(temp['date'])
temp_monthly= temp.set_index('date').resample('ME').mean()

In [ ]:
tempd=datesync(temp_monthly)

In [ ]:
temp_monthly.to_csv('temperature_final.csv')

runoff

In [ ]:
runoff1= pd.read_csv('raw_data/runoff.csv')
runoff1['date']= pd.to_datetime(runoff1['date'])
runoff_monthly= runoff1.set_index('date').resample('ME').sum()

In [ ]:
runoff_monthly.plot()

In [ ]:
runoff_monthly.to_csv('runoff_final.csv')

In [ ]:
runoff_aggr= pd.read_csv('raw_data/runoff_monthlyagrr.csv')
runoff_aggr['date']= pd.to_datetime(runoff_aggr['date'])
runoff_monthlyaggr= runoff_aggr.set_index('date').resample('ME').sum()

In [ ]:
runoff_monthlyaggr.plot()

In [ ]:
import pandas as pd
df= pd.read_csv('final_data_physics_baseline/ndvi_final.csv')
dfdew= pd.read_csv('final_data_physics_baseline/dewpoint_temp_final.csv')
dfrad= pd.read_csv('final_data_physics_baseline/radiation_final.csv')

display(df.head(), dfdew.head(), dfrad.head())

In [ ]:
def norm(dff, col):
        normalized_col = f'{col}_normalized'
        epsilon = 1e-10  # Very small number (0.0000000001)

        df[normalized_col]= (dff[col]-dff[col].min())/(dff[col].max()-dff[col].min())+ epsilon
        return df, dff[col].min()

In [ ]:
norm(dfrad, 'MJ/m2')

In [ ]:
norm(dfdew, 'mean_dew')

In [ ]:
norm(df, 'NDVI')

In [ ]:
df1=df.drop(columns= 'NDVI')

In [ ]:
df1.to_csv('et_loss.csv', index=False)

In [ ]:
df1['et_loss']= df['NDVI_normalized']*(1-df['mean_dew_normalized'])*df['MJ/m2_normalized']

In [ ]:
df1.head()

In [ ]:
df2= df1.drop(columns=['NDVI_normalized','mean_dew_normalized','MJ/m2_normalized'])

In [ ]:
row= df1.loc[df1['date'] == '2024-12-31']
print(row)

In [ ]:
df2.to_csv('et_loss.csv')

In [ ]:
import pandas as pd
tempp=pd.read_csv('final_data_physics_baseline/temperature_final.csv')
tempp.head()

In [ ]:
threshold=273
count= (tempp['temp_mean']> threshold).sum()
count

In [ ]:
tempp['dd']=tempp['temp_mean'].apply(lambda t: max(t-273, 0))

In [ ]:
threshold= 0
count= (tempp['dd']> threshold).sum()
count

In [ ]:
tempp.head(20)

In [ ]:
from utils import datesync
datesync(df=tempp)

In [ ]:
dew= pd.read_csv('final_data_physics_baseline/dewpoint_temp_final.csv')
et = pd.read_csv('final_data_physics_baseline/et_loss.csv')
ndvi = pd.read_csv('final_data_physics_baseline/ndvi_final.csv')
precip= pd.read_csv('final_data_physics_baseline/precip_monthly_final.csv')
radiation = pd.read_csv('final_data_physics_baseline/radiation_final.csv')
sca = pd.read_csv('final_data_physics_baseline/sca_monthly_final.csv')

In [ ]:

display(dew.head(), et.head(), ndvi.head(), precip.head(), radiation.head(), sca.head(), tempp.head())

In [ ]:
physics_base = pd.DataFrame()

physics_base['date'] = dew['date']

# Add multiple columns from different DataFrames
physics_base['dewpoint'] = dew['mean_dew']
physics_base['et_loss'] = et['et_loss']
physics_base['ndvi'] = ndvi['NDVI']
physics_base['precipitation'] = precip['precip_mm_hr']
physics_base['radiation'] = radiation['MJ/m2']
physics_base['sca'] = sca['sca_km2']
physics_base['dd'] = tempp['dd']
physics_base['temp'] = tempp['temp_mean']

In [ ]:
runoff = pd.read_csv('final_data_physics_baseline/runoff_final.csv')
physics_base['runoff']= runoff['runoff']

In [ ]:
physics_base.count()

In [ ]:
physics_base.to_csv('physics_basedate.csv')

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt


# Scatter plot
plt.figure(figsize=(10, 6))
plt.plot(tempp['date'], tempp['temp_mean'])
plt.xlabel('Column 1')
plt.ylabel('Column 2')
plt.title('Scatter Plot')
plt.show()

# bias correction

In [10]:
# runoff ~5%
import pandas as pd
runoff= pd.read_csv('final_data_physics_baseline/runoff_final.csv')
runoff

           date    runoff
0    2000-06-30  1.009778
1    2000-07-31  0.543038
2    2000-08-31  0.373700
3    2000-09-30  0.196165
4    2000-10-31  0.145426
..          ...       ...
301  2025-07-31  0.821420
302  2025-08-31  0.507926
303  2025-09-30  0.268507
304  2025-10-31  0.159146
305  2025-11-30  0.097332

[306 rows x 2 columns]

In [11]:
runoff['runoff_corrected'] = runoff['runoff']*0.95

In [12]:
run = runoff.drop(columns= 'runoff')

In [13]:
run.head()

         date  runoff_corrected
0  2000-06-30          0.959289
1  2000-07-31          0.515886
2  2000-08-31          0.355015
3  2000-09-30          0.186357
4  2000-10-31          0.138155

In [14]:
run.to_csv('runoff_final.csv')

In [15]:
phy = pd.read_csv('final_data_physics_baseline/physics_basedate.csv')

In [16]:
phy.head()

,Unnamed: 0,date,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp,runoff
0,0,2000-06-30,270.274111,0.035384,0.167895,1.081265,8552.215167,15695.091988,0.0,253.924696,1.009778
1,1,2000-07-31,275.634907,0.005471,0.214835,2.074423,8945.476526,6188.434963,0.0,251.865719,0.543038
2,2,2000-08-31,273.643363,0.016486,0.171795,1.208544,8787.250911,10114.130241,0.0,256.913569,0.373700
3,3,2000-09-30,266.780844,0.040531,0.148384,0.857759,7687.016192,12888.810599,0.0,263.094486,0.196165
4,4,2000-10-31,259.412862,0.029951,0.113129,0.231264,5685.865842,19583.623736,0.0,271.551964,0.145426

In [17]:
phy.drop(columns='runoff')

,Unnamed: 0,date,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp
0,0,2000-06-30,270.274111,3.538449e-02,0.167895,1.081265,8552.215167,15695.091988,0.000000,253.924696
1,1,2000-07-31,275.634907,5.471431e-03,0.214835,2.074423,8945.476526,6188.434963,0.000000,251.865719
2,2,2000-08-31,273.643363,1.648614e-02,0.171795,1.208544,8787.250911,10114.130241,0.000000,256.913569
3,3,2000-09-30,266.780844,4.053131e-02,0.148384,0.857759,7687.016192,12888.810599,0.000000,263.094486
4,4,2000-10-31,259.412862,2.995059e-02,0.113129,0.231264,5685.865842,19583.623736,0.000000,271.551964
...,...,...,...,...,...,...,...,...,...,...
301,301,2025-07-31,276.245179,2.960460e-11,0.226520,2.587007,8614.751440,9439.384406,0.000000,255.264012
302,302,2025-08-31,274.605137,1.141355e-02,0.191359,3.429811,8286.906126,11256.247468,0.000000,258.528594
303,303,2025-09-30,269.724878,3.859465e-02,0.183518,0.934844,7608.462356,16691.511776,0.000000,264.581760
304,304,2025-10-31,258.703766,5.800479e-02,0.183481,0.750958,4767.830711,34178.031966,0.000000,271.044402
305,305,2025-11-30,250.593196,3.584063e-02,0.116770,0.205526,4487.089469,26484.525266,4.179476,277.179476

In [20]:
phy['runoff']= runoff['runoff_corrected']

In [21]:
phy

,Unnamed: 0,date,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp,runoff
0,0,2000-06-30,270.274111,3.538449e-02,0.167895,1.081265,8552.215167,15695.091988,0.000000,253.924696,0.959289
1,1,2000-07-31,275.634907,5.471431e-03,0.214835,2.074423,8945.476526,6188.434963,0.000000,251.865719,0.515886
2,2,2000-08-31,273.643363,1.648614e-02,0.171795,1.208544,8787.250911,10114.130241,0.000000,256.913569,0.355015
3,3,2000-09-30,266.780844,4.053131e-02,0.148384,0.857759,7687.016192,12888.810599,0.000000,263.094486,0.186357
4,4,2000-10-31,259.412862,2.995059e-02,0.113129,0.231264,5685.865842,19583.623736,0.000000,271.551964,0.138155
...,...,...,...,...,...,...,...,...,...,...,...
301,301,2025-07-31,276.245179,2.960460e-11,0.226520,2.587007,8614.751440,9439.384406,0.000000,255.264012,0.780349
302,302,2025-08-31,274.605137,1.141355e-02,0.191359,3.429811,8286.906126,11256.247468,0.000000,258.528594,0.482529
303,303,2025-09-30,269.724878,3.859465e-02,0.183518,0.934844,7608.462356,16691.511776,0.000000,264.581760,0.255081
304,304,2025-10-31,258.703766,5.800479e-02,0.183481,0.750958,4767.830711,34178.031966,0.000000,271.044402,0.151189
305,305,2025-11-30,250.593196,3.584063e-02,0.116770,0.205526,4487.089469,26484.525266,4.179476,277.179476,0.092465

In [22]:
tempp= pd.read_csv('final_data_physics_baseline/temperature_final.csv')

In [23]:
tempp.head()

         date    max_temp    min_temp   temp_mean
0  2000-01-31  258.226435  249.122225  253.924696
1  2000-02-29  256.269613  246.986457  251.865719
2  2000-03-31  261.712874  251.017361  256.913569
3  2000-04-30  268.621727  256.132294  263.094486
4  2000-05-31  276.870840  264.610294  271.551964

In [24]:
tempp['max_temp'] = tempp['max_temp'] + 2
tempp['min_temp'] = tempp['min_temp'] + 2
tempp['mean_temp'] = tempp['temp_mean'] + 2

In [25]:
phy['temp']= tempp['mean_temp']

In [26]:
phy.head()

,Unnamed: 0,date,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp,runoff
0,0,2000-06-30,270.274111,0.035384,0.167895,1.081265,8552.215167,15695.091988,0.0,255.924696,0.959289
1,1,2000-07-31,275.634907,0.005471,0.214835,2.074423,8945.476526,6188.434963,0.0,253.865719,0.515886
2,2,2000-08-31,273.643363,0.016486,0.171795,1.208544,8787.250911,10114.130241,0.0,258.913569,0.355015
3,3,2000-09-30,266.780844,0.040531,0.148384,0.857759,7687.016192,12888.810599,0.0,265.094486,0.186357
4,4,2000-10-31,259.412862,0.029951,0.113129,0.231264,5685.865842,19583.623736,0.0,273.551964,0.138155

In [30]:
tempp['dd'] = tempp['mean_temp'].apply(lambda x: max(x-273,0))

In [31]:
phy['dd']= tempp['dd']

In [32]:
phy.head()

,Unnamed: 0,date,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp,runoff
0,0,2000-06-30,270.274111,0.035384,0.167895,1.081265,8552.215167,15695.091988,0.000000,255.924696,0.959289
1,1,2000-07-31,275.634907,0.005471,0.214835,2.074423,8945.476526,6188.434963,0.000000,253.865719,0.515886
2,2,2000-08-31,273.643363,0.016486,0.171795,1.208544,8787.250911,10114.130241,0.000000,258.913569,0.355015
3,3,2000-09-30,266.780844,0.040531,0.148384,0.857759,7687.016192,12888.810599,0.000000,265.094486,0.186357
4,4,2000-10-31,259.412862,0.029951,0.113129,0.231264,5685.865842,19583.623736,0.551964,273.551964,0.138155

In [33]:
phy.to_csv('phy_final_corrected_data.csv')

In [34]:
runoff= pd.read_csv('final_data_physics_baseline/runoff_final.csv')
runoff.head()

   Unnamed: 0        date  runoff_corrected
0           0  2000-06-30          0.959289
1           1  2000-07-31          0.515886
2           2  2000-08-31          0.355015
3           3  2000-09-30          0.186357
4           4  2000-10-31          0.138155

In [36]:
runoff['runoff_corrected'].map(lambda x: x*165000*1000000)

0      1.582827e+11
1      8.512119e+10
2      5.857747e+10
3      3.074887e+10
4      2.279557e+10
           ...
301    1.287576e+11
302    7.961737e+10
303    4.208840e+10
304    2.494614e+10
305    1.525673e+10
Name: runoff_corrected, Length: 306, dtype: float64

In [37]:
runoff.head()

   Unnamed: 0        date  runoff_corrected
0           0  2000-06-30          0.959289
1           1  2000-07-31          0.515886
2           2  2000-08-31          0.355015
3           3  2000-09-30          0.186357
4           4  2000-10-31          0.138155

In [38]:
sca= pd.read_csv('final_data_physics_baseline/sca_monthly_final.csv')

In [40]:
sca['sca_m2']= sca['sca_km2'].map(lambda x: x*1000000)

In [42]:
sca.head()

         date       sca_km2        sca_m2
0  2000-06-30  15695.091988  1.569509e+10
1  2000-07-31   6188.434963  6.188435e+09
2  2000-08-31  10114.130241  1.011413e+10
3  2000-09-30  12888.810599  1.288881e+10
4  2000-10-31  19583.623736  1.958362e+10

In [43]:
phy= pd.read_csv('final_data_physics_baseline/phy_final_corrected_data.csv')

In [44]:
phy.head()

,Unnamed: 0.1,Unnamed: 0,date,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp,runoff
0,0,0,2000-06-30,270.274111,0.035384,0.167895,1.081265,8552.215167,15695.091988,0.000000,255.924696,0.959289
1,1,1,2000-07-31,275.634907,0.005471,0.214835,2.074423,8945.476526,6188.434963,0.000000,253.865719,0.515886
2,2,2,2000-08-31,273.643363,0.016486,0.171795,1.208544,8787.250911,10114.130241,0.000000,258.913569,0.355015
3,3,3,2000-09-30,266.780844,0.040531,0.148384,0.857759,7687.016192,12888.810599,0.000000,265.094486,0.186357
4,4,4,2000-10-31,259.412862,0.029951,0.113129,0.231264,5685.865842,19583.623736,0.551964,273.551964,0.138155

In [45]:
phy['sca_m2']= sca['sca_m2']

In [46]:
phy.head()

,Unnamed: 0.1,Unnamed: 0,date,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp,runoff,sca_m2
0,0,0,2000-06-30,270.274111,0.035384,0.167895,1.081265,8552.215167,15695.091988,0.000000,255.924696,0.959289,1.569509e+10
1,1,1,2000-07-31,275.634907,0.005471,0.214835,2.074423,8945.476526,6188.434963,0.000000,253.865719,0.515886,6.188435e+09
2,2,2,2000-08-31,273.643363,0.016486,0.171795,1.208544,8787.250911,10114.130241,0.000000,258.913569,0.355015,1.011413e+10
3,3,3,2000-09-30,266.780844,0.040531,0.148384,0.857759,7687.016192,12888.810599,0.000000,265.094486,0.186357,1.288881e+10
4,4,4,2000-10-31,259.412862,0.029951,0.113129,0.231264,5685.865842,19583.623736,0.551964,273.551964,0.138155,1.958362e+10